twitch:
  client-id: ""
  access-token: ""
  refresh-token: ""
  default-settings:
    mode: "chat"
    interval-seconds: 60
    event-seconds: 16
    max-voteable-events: 4
    show-poll-in-minecraft: false
