# Instructions on how to get the Twitch data (client-id, access-token, refresh-token):
# 1. Go to the pre-configured link: https://twitchtokengenerator.com/quick/8f7Z4nSr7H
# 2. Log in with your Twitch account (it only asks for the 'user:read:chat' permission).
# 3. Copy the 3 pieces of data obtained (Client ID, Access Token, Refresh Token) and paste them below.
twitch:
  client-id: ""
  access-token: ""
  refresh-token: ""
  default-settings:
    interval-seconds: 90
    event-seconds: 60
    vote-seconds: 30
    max-voteable-events: 4
